frontend/models/Invoice.php
<?php

namespace frontend\models;
use common\models\User;
use Yii;
use common\models\Packages;
use app\models\Subscription;

/**
 * This is the model class for table "invoices".
 *
 * @property integer $id
 * @property integer $package_id
 * @property integer $invoice_id
 * @property double $amount
 * @property string $transaction_id
 * @property integer $status
 */
class Invoice extends \yii\db\ActiveRecord
{

  const STATUS_INVOICE_PAID = 1;
  const STATUS_INVOICE_PENDING = 0;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'invoice';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
        ];
    }

    public function getPackageDetails()
    {
      return $this->hasOne(Packages::className(), ['id' => 'package_id']);
    }

    public function getUserModel()
    {
      return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getSubscriptionDetail()
    {
      return $this->hasOne(Subscription::className(), ['id' => 'subscription_id']);
    }
}

frontend/models/Invoices.php
<?php

namespace frontend\models;

use Yii;
use common\models\User;

/**
 * This is the model class for table "invoices".
 *
 * @property integer $id
 * @property integer $package_id
 * @property integer $invoice_id
 * @property double $amount
 * @property string $transaction_id
 * @property integer $status
 */
class Invoices extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'invoices';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['package_id', 'invoice_id', 'amount', 'transaction_id', 'status'], 'required'],
            [['package_id', 'invoice_id', 'status'], 'integer'],
            [['amount'], 'string'],
            [['transaction_id'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'package_id' => 'Package ID',
            'invoice_id' => 'Invoice ID',
            'amount' => 'Amount',
            'transaction_id' => 'Transaction ID',
            'status' => 'Status',
        ];
    }

    public function getUserModel()
    {
      return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
}

frontend/controllers/InvoiceController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use common\models\User;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\Packages;
use frontend\models\Invoices;
use app\models\Leads;
use common\models\LiveChat_API;
use common\models\CustomPackageRange;
use common\models\PackageUser;
use frontend\models\Invoice;
use common\models\StripeLog;
use app\models\Subscription;
//use mPDF;
/**
 * Invoice controller
 */

class InvoiceController extends Controller
{
	public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],

            'access' => [
                'class' => AccessControl::className(),
                'except' => ['test', 'update-invoice-status'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'print-pay-as-you-go-pdf', 'invoice-listing',
                        			'print-pdf', 'failed-listing', 'success', 'paybysavedcard', 'payperlead',
                        			'payperleadbysavedcard', 'pay-custom-package-by-saved-card'],
                        'roles' => ['@'],
                    ],
                     [
                        'allow' => true,
                        'actions' => ['savecard'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

     public function beforeAction($action)
    {
        if(!parent::beforeAction($action)) {
            return false;
        }

		LoginForm::userAssitLogin();


        return true;
    }

    public function render($view, $params)
    {
		$params = LoginForm::userAssitLogout($params);
        // before render
        return parent::render($view, $params);
    }

	public function actionIndex(){
		$this->layout = 'kosmoouter';
		$success	  = "";
		$error		  = "";



		$this->layout = 'kosmleadsandchats';
		if(in_array(Yii::$app->user->identity->role, [User::ROLE_ADMIN, User::ROLE_SUBADMIN])) {
			$invoices	  = Invoices::find()->orderBy('id DESC')->all();

			return $this->render('index', ['success' => $success, 'error' => $error, 'invoices' => $invoices]);
		}else{
			$invoices	  = Invoices::find()->where(['user_id' => Yii::$app->user->id])->orderBy('id DESC')->all();

			return $this->render('index', ['success' => $success, 'error' => $error, 'invoices' => $invoices]);
		}
	}

	public function actionPrintPdf(){
     $invoice_id = Yii::$app->request->get('id');
		 $invoice = Invoice::findOne($invoice_id);
		 $userData 	 = User::findOne($invoice->user_id);
		 if($invoice->gst_percent!=0){
			 $gst = '<tr>
					 <td colspan="3"></td>
					 <td class="mono">GST '.$invoice->gst_percent.'%</td>
					 <td class="mono">'.$invoice->gst_charge.'</td>
			 </tr>';
		 }else{
			 $gst = '';
		 }
      if($invoice->invoice_status==1){
				$status = 'Paid';
			}else{
				$status = '';
			}
		 if($invoice->extra_lead_consumed>0){
			 $extra = '<tr>
					 <td style="text-align:left; padding-left:10px; width:8%;">2</td>
					 <td style="text-align:left; padding-left:10px;">Extra Lead<br />
					 <td class="mono" style="width:15%;">'.$invoice->extra_lead_consumed.'</td><td style="width:15%;" class="mono">'.$invoice->extra_per_lead_amount.'</td>
					 <td style="width:15%;" class="mono">'.$invoice->extra_lead_consumed*$invoice->extra_per_lead_amount.'</td>
			 </tr>';
		 }else{
			 $extra = '';
		 }
		 //echo '<pre>';print_r($invoice->packageDetails);exit;
		 if($invoice->advance_payment_status==1){
			 $table = '<tr>
					 <td style="text-align:left; padding-left: 10px; width:8%;">1</td>
					 <td style="text-align:left; padding-left:10px;">'.$invoice->packageDetails->package_name.'<br /></td>
					 <td class="mono" style="width:15%;">'.$invoice->allocated_lead.'</td><td style="width:15%;" class="mono">'.$invoice->advanced_payment.'</td>
					 <td style="width:15%;" class="mono">'.$invoice->remaining_days_total_amount.'</td>
			 </tr>
			 <tr>
					 <td colspan="3"></td>
					 <td></td>
					 <td></td>
			 </tr>
			 '.$extra.''.$gst;
		 }else{
			 $table = '
			 <tr>
					 <td style="text-align:left; padding-left: 10px; width:8%;">1</td>
					 <td style="text-align:left; padding-left:10px;">'.$invoice->packageDetails->package_name.'<br /></td>
					 <td class="mono" style="width:15%;">'.$invoice->allocated_lead.'</td><td style="width:15%;" class="mono">'.$invoice->advanced_payment.'</td>
					 <td style="width:15%;" class="mono">'.round($invoice->remaining_days_total_amount).'</td>
			 </tr>
			 <tr>
					 <td colspan="3"></td>
					 <td></td>
					 <td></td>
			 </tr>
			 '.$extra.''.$gst;
		 }

     if($invoice->invoice_status==0 && $invoice->automatic_charge_status!=1){
         //$duedate = '<h3>Due Date: '.date('d-F-Y',strtotime('+4 days', $invoice->created_at)).'</h3><p>Electronic Payment Preferred. Please use the Invoice number in the reference to ensure correct allocation of your payment.<br />Thank you for your custom.</p><p>Westpac</p><p>BSB: 033120</p><p>A/C#: 361629</p>';

				 $duedate='';
		 }else{
         $duedate='';
		 }

        //require_once('../mpdf_mpdf_7.1.4.0_require');
       // require_once '../mpdf_mpdf_7.1.4.0_require/vendor/autoload.php';
        $mpdf = new \Mpdf\Mpdf();
		 //$mpdf = new \Mpdf\Mpdf();
		 $mpdf->SetDisplayMode('fullpage');
		 $mpdf->list_indent_first_level = 0;
     $mpdf->WriteHTML('<!DOCTYPE html>
		 <html>
		 <head>
		     <title>Print Invoice</title>
		     <style>
		         *
		         {
		             margin:0;
		             padding:0;
		             font-family:Arial;
		             font-size:10pt;
		             color:#000;
		         }
		         body
		         {
		             width:100%;
		             font-family:Arial;
		             font-size:10pt;
		             margin:0;
		             padding:0;
		         }

		         p
		         {
		             margin:0;
		             padding:0;
		         }

		         #wrapper
		         {
		             width:150mm;
		             margin:0 15mm;
		         }

		         .page
		         {
		             height:297mm;
		             width:210mm;
		             page-break-after:always;
		         }

		         table
		         {
		             border-left: 1px solid #ccc;
		             border-top: 1px solid #ccc;

		             border-spacing:0;
		             border-collapse: collapse;

		         }

		         table td
		         {
		             border-right: 1px solid #ccc;
		             border-bottom: 1px solid #ccc;
		             padding: 2mm;
		         }

		         table.heading
		         {
		             height:50mm;
		         }

		         h1.heading
		         {
		             font-size:14pt;
		             color:#000;
		             font-weight:normal;
		         }

		         h2.heading
		         {
		             font-size:9pt;
		             color:#000;
		             font-weight:normal;
		         }

		         hr
		         {
		             color:#ccc;
		             background:#ccc;
		         }

		         #invoice_body
		         {
		             height: 80mm;
		         }

		         #invoice_body , #invoice_total
		         {
		             width:100%;
		         }
		         #invoice_body table , #invoice_total table
		         {
		             width:100%;
		             border-left: 1px solid #ccc;
		             border-top: 1px solid #ccc;

		             border-spacing:0;
		             border-collapse: collapse;

		             margin-top:5mm;
		         }

		         #invoice_body table td , #invoice_total table td
		         {
		             text-align:center;
		             font-size:9pt;
		             border-right: 1px solid #ccc;
		             border-bottom: 1px solid #ccc;
		             padding:2mm 0;
		         }

		         #invoice_body table td.mono  , #invoice_total table td.mono
		         {
		             text-align:left;
		             padding-right:3mm;
								 padding-left: 2mm;
		             font-size:10pt;
		         }

		         #footer
		         {
		             width:180mm;
		             margin:0 15mm;
		             padding-bottom:3mm;
		         }
		         #footer table
		         {
		             width:100%;
		             border-left: 1px solid #ccc;
		             border-top: 1px solid #ccc;

		             background:#eee;

		             border-spacing:0;
		             border-collapse: collapse;
		         }
		         #footer table td
		         {
		             width:25%;
		             text-align:center;
		             font-size:9pt;
		             border-right: 1px solid #ccc;
		             border-bottom: 1px solid #ccc;
		         }
		     </style>
		 </head>
		 <body>
		 <div id="wrapper">

		     <p style="text-align:center; font-weight:bold; padding-top:5mm;">
				 </p>
				 <p style="text-align:center; font-weight:bold; padding-top:5mm;">
				 <!--<img src="/assets/CM-logo-new.png" width="200" />-->
				 <img src="/assets/CM-logo-new-dark.svg" width="200" />
				 </p>
		     <br />
		     <table class="heading" style="width:100%;">
		         <tr>
		             <td style="width:80mm;">
		                 <h1 class="heading">TAX INVOICE</h1>
		                 <h2 class="heading">
												'.$userData->business_name.'<br />
												'.$userData->email.'<br />
												'.$userData->website_url.'<br />

		                 </h2>
		             </td>
		             <td rowspan="2" valign="top" align="left" style="padding:3mm;">
		                 <table>
		                     <tr><td>Invoice No </td><td>'.$invoice->id.'</td></tr>
		                     <tr><td>Package Activation Date </td><td>'.date('Y-m-d',$invoice->subscriptionDetail->created_at).'</td> </tr>

frontend/views/invoice/list-admin.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
?>
<div class="ks-page-header">
          <section class="ks-title">
              <h3>Invoices</h3>
          </section>
      </div>
      <div class="ks-page-content">
        <div class="ks-page-content-body">
            <div class="ks-nav-body-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 ks-panels-column-section">
                            <div class="card">
                                <div class="card-block">
                                  <div class="card-block ks-datatable">
                                      <table id="ks-datatable" class="table table-bordered table-responsive">
                                          <thead>
                                             <tr>
                                              <th>Order</th>
                       												<th>Email</th>
                       												<!--th>agents</th-->
                       												<th>Advanced Payment</th>
                       												<th>Transaction Id</th>
                                              <th>Allocated Leads</th>
                       												<th>Extra leads Consumed</th>
                       												<th>Extra Lead Amount ($)</th>
                       												<th>Advanced Payment Status</th>
                       												<th>Transaction Currency</th>
                       												<!-- <th>Invoice Status</th> -->
                                              <th>Pending Invoice</th>
                       												<th>Automatic Charge Status</th>
                       												<th>Total Charge ($)</th>
                                              <th>Past Lead Access</th>
                       												<th>Package Activation Date</th>
                                              <th>Created Date</th>
                       												<th>Billing Date</th>
                       												<!-- <th>Payment Date</th> -->
                       												<th>Download Receipt</th>
                                            </tr>
                                          </thead>
                                          <tbody>
                                            <?php
                                            foreach($invoices as $invoice){
                                              ?>
                                            <tr>
                                              <td><?php echo $invoice->id;?></td>
                                              <td><?php echo $invoice->userModel->email;?></td>
                                              <td><?php echo $invoice->advanced_payment;?></td>
                                              <td><?php echo $invoice->stripe_payment_id;?></td>
                                              <td><?php echo $invoice->allocated_lead;?></td>
                                              <td><?php echo $invoice->extra_lead_consumed;?></td>
                                              <td><?php echo $invoice->extra_per_lead_amount;?></td>
                                              <td><?php if($invoice->advance_payment_status==1){
                                                echo 'Active';
                                              }else{
                                                echo 'Inactive';
                                              }?></td>
                                              <td><?php echo $invoice->transaction_currency;?></td>
                                              <!-- <td><?php  if($invoice->invoice_status==1){
                                                echo "Paid";
                                              }else{
                                                echo "Pending";
                                              }?></td> -->
                                              <td><?php  if($invoice->pending_invoice==0){
                                                echo "No";
                                              }else{
                                                echo "Yes";
                                              }?></td>
                                              <td><?php if($invoice->automatic_charge_status==1){
                                                echo "Automatic";
                                              }else{
                                                echo "Billing";
                                              }?></td>
                                              <td><?php echo $invoice->total_amount ?></td>
                                              <td><?php
                                              if($invoice->subscriptionDetail['show_previous_lead']==1){
                                                echo "Active";
                                              }else{
                                                echo "Inactive";
                                              }?></td>
                                              <td><?php echo date('Y-m-d',  $invoice->subscriptionDetail['created_at']);?></td>
                                              <td><?php echo date('Y-m-d H:i:s',  $invoice->created_at);?></td>
                                              <td><?php echo date('Y-m-d H:i:s',  $invoice->billing_date);?></td>
                                              <!-- <td><?php if($invoice->payment_date==0){
                                                echo "Not-Paid";
                                              }else{
                                                echo date('Y-m-d H:i:s',  $invoice->payment_date);
                                              } ?></td> -->
                                              <td><?php
                                              if($invoice->automatic_charge_status==1){
                                                  echo '<a href="'.Url::to(['invoice/print-pdf', 'id' =>$invoice->id]).'" target="_blank"><button type="button"  class="btn btn-default btn-sm"><i class="fa fa-download"></i></button></a>';
                                              }else{
                                              /*echo  '<div class="row">
                                  <button type="button" data-toggle="modal" data-target="#update_invoice" data-id="'.$invoice->id.'" class="btn btn-default btn-sm update_invoice">update</button>
                                                <a href="'.Url::to(['invoice/print-pdf', 'id' =>$invoice->id]).'" target="_blank"><button type="button"  class="btn btn-default btn-sm"><i class="fa fa-download"></i></button></a>
                                                </div>';*/
                                                echo  '<a href="'.Url::to(['invoice/print-pdf', 'id' =>$invoice->id]).'" target="_blank"><button type="button"  class="btn btn-default btn-sm"><i class="fa fa-download"></i></button></a>';
                                              }
                                              ?></td>
                                            </tr>
                                            <?php
                                          }
                                            ?>
                                          </tbody>
                                        </table>
                                      </div>
                                    </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                  </div>

                  <!---Model--->
                  <div id="update_invoice" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                      <!-- Modal content-->
                      <div class="modal-content">
                        <div class="modal-header">
                        <h4 class="modal-title">Change Invoice Status</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                          <label>Status:</label>
                        <select id="paid_status" class="form-control" >
                            <option value="3">-Select Status</option>
                          <option value="1" >Paid</option>
                          <option value="0" >Pending</option>
                        </select>
                        <br />
                        <label>Payment Date</label>
                         <input type="text" placeholder="Paid ON" class="form-control" id="paid_on">
                        </div>
                        <input type="hidden" id="invoice_id" value="">
                        <div class="modal-footer">
                        <button type="button" class="btn btn-primary change_invoice_status">Change Status</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                      </div>
                      </div>
                  </div>
                  <!---Model--->

      <?php
      $this->registerJs("

       jQuery('#paid_on').datepicker( {
         dateFormat: 'yy-mm-dd',
         changeMonth:true,
         changeYear:true}
      );

      $('.update_invoice').off('click').on('click', function(e){
        e.preventDefault();
        $('#invoice_id').val($(this).data('id'));
      });

      // $('.pdf_invoice').off('click').on('click',function(e){
      //          e.preventDefault();
      //          var invoice_id = $(this).data('id');
      // });

      $('.change_invoice_status').off('click').on('click', function(e){
        e.preventDefault();
        var invoice_id = $('#invoice_id').val();
        if(invoice_id==''){
          swal('Internal Error Please Try again latter');
          return false;
        }
        var paid_status =  $('#paid_status').val();
        var paid_on =  $('#paid_on').val();
        if(paid_status==''){
          swal('Please choose a Status');
          return false
        }
        if(paid_status=='3'){
                      swal('Please choose a Status');
                      return false
        }
        if(paid_on==''){
          swal('Please choose a Payment Date');
          return false
        }
        if(paid_status==0){
           paid_on = 0;
         }
        $.ajax({
          type: 'POST',
          url: '".Url::to(['invoice/update-invoice-status'])."',
          data: {paid_status:paid_status,
                  paid_on:paid_on
                ,invoice_id:invoice_id},
          success: function(response){
            response = JSON.parse(response)
            if(response.success == true){
              console.log(response);
              location.reload();
            }
            if(response.success == false){
              swal(response.data, 'error');
              return false;
            }
          },
          error: function(data){
            console.log(data);
            swal('Some problem occured!', 'Please try again later after sometime.', 'error');
            return false;
          },
        });
      });
      ");
      ?>

frontend/views/invoice/list-user.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
?>
<div class="ks-page-header">
          <section class="ks-title">
              <h3>Invoices</h3>
          </section>
      </div>
      <div class="ks-page-content">
        <div class="ks-page-content-body">
            <div class="ks-nav-body-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 ks-panels-column-section">
                            <div class="card">
                                <div class="card-block">
                                  <div class="card-block ks-datatable">
                                      <table id="ks-datatable" class="table table-bordered table-responsive" style="width:100%" width="100%">
                                          <thead>
                                             <tr>
                                              <th>Order</th>
                       												<th>Email</th>
                       												<!--th>agents</th-->
                       												<th>Advanced Payment</th>
                       												<th>Transaction Id</th>
                                              <th>Allocated Leads</th>
                       												<th>Extra leads Consumed</th>
                       												<th>Extra Lead Amount ($)</th>
                       												<th>Advanced Payment Status</th>
                       												<th>Transaction Currency</th>
                       												<!-- <th>Invoice Status</th> -->
                                              <th>Pending Invoice</th>
                       												<th>Automatic Charge Status</th>
                       												<th>Total Charge ($)</th>
                                              <th>Past Lead Access</th>
                       												<th>Package Activation Date</th>
                       												<th>Created At</th>
                       												<th>Billing Date</th>
                       												<!-- <th>Payment Date</th> -->
                       												<th>Download Receipt</th>
                                          </thead>
                                          <tbody>
                                            <?php
                                            foreach($invoices as $invoice){
                                              ?>
                                            <tr>
                                              <td><?php echo $invoice->id;?></td>
                                              <td><?php echo $invoice->userModel->email;?></td>
                                          <td><?php echo $invoice->advanced_payment;?></td>
                                              <td><?php echo $invoice->stripe_payment_id;?></td>
                                              <td><?php echo $invoice->allocated_lead;?></td>
                                              <td><?php echo $invoice->extra_lead_consumed;?></td>
                                              <td><?php echo $invoice->extra_per_lead_amount;?></td>
                                              <td><?php if($invoice->advance_payment_status==1){
                                                echo 'Active';
                                              }else{
                                                echo 'Inactive';
                                              }?></td>
                                              <td><?php echo $invoice->transaction_currency;?></td>
                                              <!-- <td><?php  if($invoice->invoice_status==1){
                                                echo "Paid";
                                              }else{
                                                echo "Pending";
                                              }?></td> -->
                                              <td><?php  if($invoice->pending_invoice==0){
                                                echo "No";
                                              }else{
                                                echo "Yes";
                                              }?></td>
                                              <td><?php if($invoice->automatic_charge_status==1){
                                                echo "Automatic";
                                              }else{
                                                echo "Billing";
                                              }?></td>
                                              <td><?php echo $invoice->total_amount ?></td>
                                              <td><?php  if($invoice->subscriptionDetail->show_previous_lead==1){
                                                echo "Active";
                                              }else{
                                                echo "Inactive";
                                              }?></td>
                                              <td><?php echo date('Y-m-d',  $invoice->subscriptionDetail->created_at);?></td>
                                              <td><?php echo date('Y-m-d H:i:s',  $invoice->created_at);?></td>
                                              <!-- <td><?php  echo date('Y-m-d H:i:s',  $invoice->created_at);?></td> -->
                                              <td><?php echo date('Y-m-d H:i:s',  $invoice->billing_date);?></td>
                                              <!-- <td><?php if($invoice->payment_date==0){
                                                echo "Not-Paid";
                                              }else{
                                                echo date('Y-m-d H:i:s',  $invoice->payment_date);
                                              } ?></td> -->
                                              <td>
                                                <?php
                                                  echo '<a href="'.Url::to(['invoice/print-pdf', 'id' =>$invoice->id]).'" target="_blank"><button type="button"  class="btn btn-default btn-sm"><i class="fa fa-download"></i></button></a>';
                                              ?>
                                              </td>
                                            </tr>
                                            <?php
                                          }
                                            ?>
                                          </tbody>
                                        </table>
                                      </div>
                                    </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                  </div>




      <?php
      $this->registerJs("

      ");
      ?>