frontend/models/Chatstat.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "chatstats".
 *
 * @property integer $id
 * @property string $business_name
 * @property integer $group
 * @property integer $invites
 * @property integer $chats
 * @property integer $leads
 * @property integer $greeting_chats
 * @property integer $visitor_chats
 * @property string $record_date
 */
class Chatstat extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'chatstats';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['group', 'record_date'], 'required'],
            [['group', 'invites', 'chats', 'leads', 'greeting_chats', 'visitor_chats'], 'integer'],
            [['record_date'], 'safe'],
            [['business_name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'business_name' => 'Business Name',
            'group' => 'Group',
            'invites' => 'Invites',
            'chats' => 'Chats',
            'leads' => 'Leads',
            'greeting_chats' => 'Greeting Chats',
            'visitor_chats' => 'Visitor Chats',
            'record_date' => 'Record Date',
        ];
    }
}

frontend/controllers/ChatstatController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\User;
use common\models\LiveChat_API;
use frontend\models\Chatstat;
use frontend\models\ChatstatSearch;
use yii\filters\AccessControl;

class ChatstatController extends \yii\web\Controller
{
	public function behaviors()
	{
	    return [
	        'access' => [
	            'class' => AccessControl::className(),
	            'except' => ['get-report', 'archive-cron'],
	            'rules' => [
	                [
	                    'allow' => true,
	                    'actions' => ['index', 'export'],
	                    'roles' => [User::ADMIN_ROLE, User::SUBADMIN_ROLE],
	                    'matchCallback' => function ($rule, $action) {
							return Yii::$app->user->can('viewReport');                     
                        }	                    
	                ]
	            ],
	        ],
	    ];
	}

    public function actionIndex()
    {
    	$this->layout = 'kosmoouter';
        $searchModel = new ChatstatSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionExport() {
	    $dataprovider =  Yii::$app->request->get('dataprovider');
	    $someArray = json_decode($dataprovider, true);

		$pagination = false;

	    $searchModel = new ChatstatSearch;
	    $dataProvider = $searchModel->search($someArray,$pagination);	    
	    $model =  $dataProvider->getModels();

	    if($dataProvider->getTotalCount() > 0) {
	    	$rnd = rand();
		    $filename = "chatstatreport$rnd.csv";	   
		    $file = fopen($filename,"a");

			$columns = [			  
			  'Business Name',
			  'Group',
			  'Greetings', 
			  'Total Chats',
			  'Total Leads',
			  'Chat To Lead %',
			  'Conversion Rate',
			  'Total Greeting Chats',
			  'Total Visitor Chats'   
			];
		    fputcsv($file, $columns);    

		    foreach ($model as $row) {     
		      fputcsv($file, $row);  
		    }

		    header("Cache-Control: public");
		    header("Content-Description: File Transfer");
		    header("Content-Disposition: attachment; filename=$filename");
		    header("Content-Type: application/csv");
		    header("Content-Transfer-Encoding: binary");		   
		    readfile($filename); 
	    } else {
	        Yii::$app->session->setFlash('error', 'You have not bought any lead');
	        return $this->redirect(Yii::$app->request->referrer);
	    }
    }    

    public function actionGetReport() { 
    	$date = isset($_GET['date']) ? $_GET['date'] : date('Y-m-d', strtotime(' -1 day'));
	   	
    	$API = new LiveChat_API(); 	

		$params = array();
    	$params['date_from'] = $date;
    	$params['date_to'] = $date;
    	$params['timezone'] = date_default_timezone_get();
    	$params['group_by'] = 'day';  

    	$groups = $API->groups->testGroup();
    	unset($groups[0]);
    	
    	foreach ($groups as $group) {
	   		$chatstat = new Chatstat();  	
	    	$chatstat->business_name = $group->name;
	    	$chatstat->group = $group->id;
	    	$chatstat->record_date = $date;	    	

  			$params['group'] = $group->id;

	    	$response = $API->reports->get("chats/greetings",$params);
	    	$data = get_object_vars($response);
	    	$chatstat->invites = $data[$date]->displayed;

	    	$response = $API->reports->get("chats/total_chats",$params);
	    	$data = get_object_vars($response);
	    	$chatstat->chats = $data[$date]->chats;

	    	$params['tag[]'] = 'lead'; 
	    	$response = $API->reports->get("chats/total_chats",$params);
	    	$data = get_object_vars($response);
	    	$chatstat->leads = $data[$date]->chats;
	    	unset($params['tag[]']);

	    	$response = $API->reports->get("chats/engagement",$params);
	    	$data = get_object_vars($response);
	    	$chatstat->greeting_chats = $data[$date]->chats_from_auto_invite;
	    	$chatstat->visitor_chats = $data[$date]->chats_from_immediate_start;

	    	$chatstat->save();			
		}
    }

    public function actionArchiveCron() {
    	if (!isset($_GET['date'])) {
    		exit;
    	}

    	$model = new Chatstat();
    	$record_date = '2019-03-10';

    	$query_date = strtotime($record_date .' +1 day');
    	$end_date = strtotime($_GET['date']);    	

    	if ($query_date > $end_date) {
    		exit;
    	}

    	return $this->redirect(['get-report', 'date' => date('Y-m-d', $query_date)]);
    }

}

frontend/views/chatstat/index.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\bootstrap\Modal;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\ChatstatSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Chat Stats Report';
$this->params['breadcrumbs'][] = $this->title;
?>
<!--New Design----->
<div class="ks-page-header">
            <section class="ks-title">
                <h3><?= Html::encode($this->title) ?></h3>
            </section>
        </div>

        <div class="ks-page-content">
            <div class="ks-page-content-body">
                <div class="ks-nav-body-wrapper">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-12 ks-panels-column-section">
                                <div class="card">
                                    <div class="card-block">
                                    <div class="row">
                                      <div class="col-md-8">
                                          <?php
                                            $form = ActiveForm::begin([
                                                    'method' => 'get',
                                                    'action' => Url::to(['chatstat/index']),
                                            ]);
                                          ?>
                                          <div class="row">
                                            <div class="col-sm-4">
                                              <input type="text" placeholder="Date From" class="form-control" id="datefrom" name="date_from">
                                            </div>
                                            <div class="col-sm-4">
                                              <input type="text" placeholder="Date To" class="form-control" id="dateto" name="date_to">
                                            </div>
                                            <div class="col-sm-4">
                                              <input type="submit" class="btn btn-info crange-submit" value="Submit">
                                            </div>
                                          </div>
                                        <?php ActiveForm::end(); ?>
                                      </div>
                                      <div class="col-md-4">
                                        <?php
                                          if ($dataProvider->getTotalCount()>0) {
                                            $csvdata = json_encode(Yii::$app->request->getQueryParams());
                                            echo "<a data-count='".$dataProvider->getTotalCount()."' href='".Url::to(['chatstat/export','dataprovider' => $csvdata])."' class='btn btn-primary-outline ks-light pull-right download-csv-btn'>Download CSV</a>";
                                          }                                                 
                                        ?>
                                      </div>
                                    </div>

                                      <?php Pjax::begin(['id' => 'pjax_widget']); ?>

                                      <?= GridView::widget([
                                          'dataProvider' => $dataProvider,
                                          'id' => 'pjax_widget',
                                          'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],
                                          'columns' => [
                                              ['class' => 'yii\grid\SerialColumn'],
                                              'business_name',
                                              'group',
                                              'greetings', 
                                              'total_chats',
                                              'total_leads',
                                              'chat_to_lead',
                                              'conversion_rate',
                                              'total_greeting_chats',
                                              'total_visitor_chats'   
                                          ],
                                      ]); ?>

                                    <?php Pjax::end(); ?>

                                   </div>
                              </div>

                          </div>

                      </div>
                  </div>
              </div>
          </div>
      </div>
<!--New Design----->
<?php
$this->registerCss("
  .ks-icon{
    font-size: 20px !important;
    padding-left: 7px;
  }
  .ks-icon:hover{
    color: #f00;
  }
");
$this->registerJs('
    $.pjax.reload({container:"#pjax_widget"});
    jQuery("document").ready(function(){
      jQuery("#dateto,#datefrom").datepicker( {dateFormat: "yy-mm-dd",changeMonth:true,changeYear:true} );
    });
');
?>